import type { AgentDescriptor, ConnectorDescriptor } from "@openlifewiki/protocol";

export const CONNECTOR_DESCRIPTORS = [
  {
    schema: "openlifewiki.connector-descriptor/v1",
    connectorType: "local-folder",
    displayName: "Local Folder",
    classification: ["source", "local-folder"],
    supportStatus: "supported",
    provider: {
      project: "openLifeWiki",
      publicSurface: "filesystem-adapter",
      executable: null,
      versionCommand: [],
    },
    capabilities: {
      hierarchy: true,
      pagination: "none",
      modifiedVersion: "content-hash",
      representativeMetadata: true,
      leafBodies: true,
      nodeKinds: ["directory", "file"],
    },
    scopeSchema: "openlifewiki.scope/local-folder/v1",
  },
  {
    schema: "openlifewiki.connector-descriptor/v1",
    connectorType: "github",
    displayName: "GitHub",
    classification: ["source", "github"],
    supportStatus: "supported",
    provider: {
      project: "cli/cli",
      publicSurface: "gh",
      executable: "gh",
      versionCommand: ["gh", "--version"],
    },
    capabilities: {
      hierarchy: true,
      pagination: "page",
      modifiedVersion: "provider-version",
      representativeMetadata: true,
      leafBodies: true,
      nodeKinds: ["repository", "directory", "file"],
    },
    scopeSchema: "openlifewiki.scope/github/v1",
  },
  {
    schema: "openlifewiki.connector-descriptor/v1",
    connectorType: "feishu",
    displayName: "Feishu",
    classification: ["source", "feishu"],
    supportStatus: "supported",
    provider: {
      project: "larksuite/cli",
      publicSurface: "lark-cli",
      executable: "lark-cli",
      versionCommand: ["lark-cli", "version"],
    },
    capabilities: {
      hierarchy: true,
      pagination: "cursor",
      modifiedVersion: "provider-version",
      representativeMetadata: true,
      leafBodies: true,
      nodeKinds: ["workspace", "wiki", "document", "base"],
    },
    scopeSchema: "openlifewiki.scope/feishu/v1",
  },
  {
    schema: "openlifewiki.connector-descriptor/v1",
    connectorType: "codex-history",
    displayName: "Codex History",
    classification: ["source", "codex-history"],
    supportStatus: "supported",
    provider: {
      project: "openai/codex",
      publicSurface: "app-server-v2",
      executable: "codex",
      versionCommand: ["codex", "--version"],
    },
    capabilities: {
      hierarchy: true,
      pagination: "cursor",
      modifiedVersion: "provider-version",
      representativeMetadata: true,
      leafBodies: true,
      nodeKinds: ["project", "thread"],
    },
    scopeSchema: "openlifewiki.scope/codex-history/v1",
  },
] as const satisfies readonly ConnectorDescriptor[];

export const AGENT_DESCRIPTORS = [
  {
    runtime: "codex",
    displayName: "Codex",
    mode: "native-cli",
    binary: "codex",
    projectUrl: "https://github.com/openai/codex",
  },
  {
    runtime: "claude",
    displayName: "Claude Code",
    mode: "native-cli",
    binary: "claude",
    projectUrl: "https://github.com/anthropics/claude-code",
  },
  {
    runtime: "gemini",
    displayName: "Gemini CLI",
    mode: "native-cli",
    binary: "gemini",
    projectUrl: "https://github.com/google-gemini/gemini-cli",
  },
  {
    runtime: "pi",
    displayName: "Pi",
    mode: "provider-runtime",
    binary: "pi",
    projectUrl: "https://github.com/earendil-works/pi",
  },
  {
    runtime: "openclaw",
    displayName: "OpenClaw",
    mode: "provider-runtime",
    binary: "openclaw",
    projectUrl: "https://github.com/openclaw/openclaw",
  },
  {
    runtime: "hermes",
    displayName: "Hermes Agent",
    mode: "provider-runtime",
    binary: "hermes",
    projectUrl: "https://github.com/NousResearch/hermes-agent",
  },
] as const satisfies readonly AgentDescriptor[];
